dns.upstreams=["127.0.0.1#5053"]

dns.hosts=[
  "100.60.1.1 example-device.domain.lan",
]
dns.domainNeeded=true
dns.expandHosts=true
dns.interface=eth0
dns.listeningMode=ALL

dhcp.active=true
dhcp.start=192.168.100.200
dhcp.end=192.168.100.253
dhcp.router=192.168.100.1
dhcp.leaseTime=24h
dhcp.ipv6=true

dhcp.hosts=[
  "00:18:84:1B:8E:E4,192.168.100.3,mydevice1,infinite",
  "00:18:84:1B:8E:E5,192.168.100.4,mydevice2,infinite",
  "00:18:84:1B:8E:E6,192.168.100.5,mydevice3,infinite"
]
